---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: web
    spec:
      containers:
      - image: alastairs/fibonacci:latest
        name: web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    service: web
  type: LoadBalancer